import { Dimensions, StyleSheet } from "react-native";
let { width, height } = Dimensions.get("window");
export default styles = StyleSheet.create({
  home: {
    // borderWidth: 1,
    borderColor: "red",
    // top: 0,
    width: "100%",
    flex: 1,
    // position:"relative",
    // zIndex: 0,
  },
  bgImg: {
    // borderWidth: 1,
    borderColor: "red",
    height: 600,
    // display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#15120B",
    // backgroundColor:'red',
    // zIndex: 0,
    gap: 20,
  },
  heading: {
    color: "white",
    fontSize: 35,
    fontWeight: "700",
    fontSize: width <= 768 ? 24 : 35,
  },
  subHeading: {
    color: "white",
    // fontSize: 20,
    fontSize: width <= 768 ? 15 : 18,
    // fontSize:width<=580?width*0.025:width*0.015
  },
  Tbtn: {
    color: "white",
    // fontSize: 20,
    fontSize: height * 0.025,
  },
  main: {
    // borderWidth: 2,
    borderColor: "red",
    position: "relative",
    // justifyContent:'center',
    // alignItems:"center"
  },
  cards: {
    display: "flex",
    // flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    gap: 25,
    flexWrap: "wrap",
    // position:"  ",
    top: "-40%",
    top: width <= 768 ? "0%" : "-40%",
    // flexShrink:3
    // flexGrow:'3'
    // borderWidth:2
  },
  card: {
    // borderWidth:1,
    backgroundColor: "white",
    display: "flex",
    gap: 25,
    // height: 500,
    paddingBottom: 50,
    // height: width <= 1024 ? null : null,
    width: "28%",
    width: width <= 768 ? "100%" : "28%",
    // alignItems: "flex-start",
    // justifyContent:'center',
    // padding: 40,
    padding: width <= 1024 ? 22 : 40,
    // paddingVertical: width <= 768 ? 30 : "",
  },
  c1: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 40,
    paddingHorizontal: width <= 768 ? 20 : 40,
    backgroundColor: "#F8F7F3",
    position: "relative",
    // borderWidth:2,
    // height:"45%",
  },

  Card_heading: {
    // fontSize: 25,
    fontSize: height * 0.04,
    // fontSize: width < 1024 ? 20 : 25,
    fontWeight: "800",
  },
  Card_para: {
    fontSize: height * 0.025,
    // fontSize: 18,
    color: "#62615C",
    lineHeight: 30,
  },
  bar: {
    width: "20%",
    height: 6,
    // borderWidth:1,
    backgroundColor: "#F9C349",
  },
  Card_para_1024: {
    // fontSize: 15,
  },

  c2: {
    backgroundColor: "rgb(248,247,243)",
    // flex:1,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-evenly",
    // flexWrap:'wrap',
    // width:"100%",
    // margin:'auto',
    flexDirection: width <= 768 ? "column" : "row",
    // borderWidth:2,
    padding: 40,
    alignItems: width <= 768 ? "" : "center",
    gap: width <= 768 ? 40 : 0,
  },
  c2_heading: {
    fontSize: height * 0.035,
    fontWeight: "800",
    // borderWidth:1,
  },
  numbers: {
    // flex:1,
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 20,
    // width:'70%',
    justifyContent: "space-between",
    alignItems: "center",
    // borderWidth:1,
    // flexDirection:width<=375?"column":"row"
  },
  reviews: {
    display: "flex",
    flexDirection: "row",
    // gap:10,
    alignItems: "center",
    justifyContent: "space-evenly",
    // borderWidth:2,
    width: height * 0.35,
    width: width <= 768 ? "40%" : height * 0.35,
  },
  reviews_500: {
    width: "100%",
    padding: 10,
    flexDirection: "column",
    alignItems: "",
    gap: 10,
  },
  review_num: {
    fontSize: height * 0.06,
    fontWeight: "700",
    color: "#F9C349",
  },

  review_title: {
    fontSize: height * 0.025,
    fontWeight: "700",
  },
  c3: {
    backgroundColor: "#F8F7F3",
    flex: 1,
    // borderWidth:1,
    alignItems: "center",
    paddingVertical: 60,
    justifyContent: "center",
  },
  c3_div: {
    justifyContent: "space-between",
    display: "flex",
    // flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    height: "auto",
    width: "80%",
    // borderWidth:1,
    padding: 40,
    // lineHeight:20,
    borderRadius: 5,
    gap: 20,
    backgroundColor: "white",
    justifyContent: width <= 768 ? "center" : "space-between",
    shadowColor: "#171717",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 15,
    elevation: 3,
    shadowColor: "#171717",
  },
  C3_HEADING: {
    fontSize: height * 0.04,
    textAlign: "center",
    fontSize: width <= 375 ? height * 0.024 : height * 0.04,
    fontWeight: "700",
    color: "rgb(249,195,73)",
  },
  c3_btn: {
    backgroundColor: "#F9C349",
    paddingVertical: height * 0.018,
    paddingHorizontal: height * 0.03,
    paddingHorizontal: width <= 768 ? height * 0.09 : height * 0.03,

    // paddingHorizontal: 35,
    // paddingVertical: 15,
    borderRadius: 5,
  },
  c3_btn_txt: {
    // fontSize: 20,
    fontSize: height * 0.02,
  },
});
